export const EVENT_TYPES = {
    PURCHASE_OFFER: 'PURCHASE_OFFER',
    RACKET: 'RACKET',
    FAS: 'FAS',
    SHARES: 'SHARES',
    FINE: 'FINE'
};

export const EVENTS = [
    EVENT_TYPES.PURCHASE_OFFER,
    EVENT_TYPES.RACKET,
    EVENT_TYPES.FAS,
    EVENT_TYPES.SHARES,
    EVENT_TYPES.FINE,
];